### ISSUE TITLE
Server crash at 1.15.2

### ISSUE THREAD

**Issue by RealCorebb** [pentantan/TofuCraftReload-1.14.4#1]
#### MOD版本 - Mod version: 
TofuCraftReload-1.15.2-0.0.0.7.0

#### Forge版本 - Forge version:
31.1.41

#### 单人/多人游戏？ - Singleplayer or Multiplayer:
Multiplayer,Forge

## 崩溃报告的链接 - Link to full crash log
Description: Ticking entity

java.lang.NoSuchMethodError: baguchan.mcmod.tofucraft.entity.multipart.ZundamaEntity.func_208000_a(FI)V
	at baguchan.mcmod.tofucraft.entity.multipart.ZunsyEntity.movePart(ZunsyEntity.java:203) ~[?:1.15.2-0.0.0.7.0] {re:classloading}
	at baguchan.mcmod.tofucraft.entity.multipart.ZunsyEntity.func_70636_d(ZunsyEntity.java:156) ~[?:1.15.2-0.0.0.7.0] {re:classloading}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2104) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:entity.block_cache.MixinLivingEntity,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinLivingEntity,pl:mixin:APP:performant.mixins.json:entity.LivingEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:274) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:entity.MobEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:600) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinServerWorld,pl:mixin:APP:lithium.mixins.json:fast_tick_scheduler.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217390_a(World.java:536) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinWorld,pl:mixin:APP:performant.mixins.json:world.WorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:401) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,xf:fml:quark:change-sleeping-player-count,xf:fml:quark:add-rave-hook,pl:mixin:APP:lithium.mixins.json:avoid_allocations.MixinServerWorld,pl:mixin:APP:lithium.mixins.json:fast_tick_scheduler.MixinServerWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:849) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241] {}

#### 产生Bug的步骤 - How to reproduce:
Just go to someplaces of Tofucraft's world. It seems that the server do not have the method : setHeadRotation

**Comment by pentantan** [comment]
Does 0.0.0.7.3 cause a similar crash when spawning zunsy?
Please let me know if something similar happens in 0.0.0.7.3

**Comment by pentantan** [comment]
fixed in 0.0.0.7.5
